{
  'printWidth': 100,
  'tabWidth': 2,
  'useTabs': false,
  'semi': true,
  'singleQuote': true,
  'jsxSingleQuote': true,
  'trailingComma': 'es5',
  'bracketSpacing': true,
  'bracketSameLine': false,
  'jsxBracketSameLine': false,
  'arrowParens': 'always',
  'proseWrap': 'always',
  'singleAttributePerLine': false,
  'importOrder': [
      '<THIRD_PARTY_MODULES>',
      # "^redux/(.*)$",
      '^@/middlewares(.*)',
      '^service/(.*)$',
      '^libs/(.*)$',
      '^hooks/(.*)$',
      '^helpers/(.*)$',
      '^assets/(.*)$',
      '^data/(.*)$',
      '^styles/(.*)$',
      '^components/(.*)$',
      '^types$',
      '^./(.*)$',
    ],
  'importOrderSeparation': true,
  'importOrderSortSpecifiers': true,
}
